### ISSUE TITLE
Would it be possible to integrate Mercury?

### ISSUE THREAD

**Issue by sardaukar** [rachel-sharp/feedbin#8]
They don't see to give out keys anymore.

**Comment by rach-sharp** [comment]
Ahh I did not realise that API had deprecated! It should be possible, I'll look into it a little later this week when I have time

**Comment by cwmke** [comment]
It looks like one of Feedbin's maintainers is already working on it upstream.

https://github.com/benubois/mercury-parser

**Comment by benubois** [comment]
Feedbin does indeed use the open-source Mercury project. I'm running it as a separate service since it's a Node.js app. That's also [open-source](https://github.com/feedbin/extract).

**Comment by agucova** [comment]
I'm thinking of spinning up a AWS Lambda function for it, but it's suboptimal. https://github.com/mahboubii/serverless-mercury-parser

**Comment by nitinthewiz** [comment]
@benubois does your [EXTRACT_HOST solution](https://github.com/feedbin/feedbin/blob/a4b59bb2c4e89e2ebd778404566ee9f9fe4b448d/.env.test), work right now? What is the EXTRACT_SECRET there? 

I'm asking because I use [this docker container](https://hub.docker.com/r/wangqiru/mercury-parser-api) to run mercury locally for my tt-rss instance.

The way it works right now is pretty straightforward. The following just works on my local instance, without any keys/secret - 

http://192.168.194.5:3000/parser?url=https://lithub.com/my-year-of-writing-anonymously/

**Comment by benubois** [comment]
Hi @nitinthewiz,

> does your EXTRACT_HOST solution, work right now? 

Yes! That's what Feedbin uses.

> What is the EXTRACT_SECRET there?

That's the secret key to create signed-urls. The [readme](https://github.com/feedbin/extract) explains how it works.

> The way it works right now is pretty straightforward. The following just works on my local instance, without any keys/secret 

OK, sounds like you're all set then.

**Comment by nitinthewiz** [comment]
Excellent! Thanks!

**Comment by nitinthewiz** [comment]
I had some trouble setting up freedbin, so once I got it right, I did a writeup for you all [here](https://www.nitinkhanna.com/notes-on-setting-up-freedbin/). I ended up not using @benubois' Extract service, because @rach-sharp's current code doesn't support it. It does, however support a self-hosted Mercury Service, which you can find [here](https://hub.docker.com/r/wangqiru/mercury-parser-api).

Cheers!
